config/routes.rb
Rails.application.routes.draw do
  get "/", to: "static#welcome"
  get "/pets", to: "pets#index"
  get "/pets/:id", to: "pets#show", as: "pet"
  get "/dogs", to: "pets#dog"
  get "/cats", to: "pets#cat"
  get "/birds", to: "pets#bird"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
require 'time'
require 'date'
class Pet < ApplicationRecord

    def age
        Time.now.year - self.year_of_birth
    end

    def good_or_bad
        return self.good_with_kids ? "Good with children" : "Prefers a home without children"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def dog
    @pets =  Pet.select {|pet| pet.species == "dog"}
    render :index
  end

  def cat
    @pets =  Pet.select {|pet| pet.species == "cat"}
    render :index

  end

  def bird
    @pets =  Pet.select {|pet| pet.species == "bird"}
    render :index
  end

  def show
    @pet = Pet.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
    
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PurrfectPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/index.html.erb
<h1> Pets: </h1>

<ul>
    <% @pets.each do |pet| %>
        <li> <%= link_to pet.name, pet_path(pet) %> </li>
    <% end %>
</ul>

app/views/pets/show.html.erb
  <img src= <%= "#{@pet.picture}" %> alt= "A picture of the animal." />
  <h1><%= "#{@pet.name} the #{@pet.species}" %></h1>

  <p> <%= @pet.age %>  </p>
  <p> <%= @pet.good_or_bad %> </p>
  <%= link_to("Back to index", pets_path) %>